telegram:
  bot_token: 8296923394:AAH4GIdVUFp14kpAA0ifqaDwRErsJKu6kls
  chat_id: '6574539700'
  message_delay: 0.5
  display:
    show_prices: true
    show_trend_24h: true
    show_trend_7d: true
    show_recommendations: true
  thresholds:
    buy_24h: 2.0
    sell_24h: -2.0
    buy_7d: 5.0
    sell_7d: -5.0
crypto:
  symbols:
  - BTC
  - ETH
  - SOL
  investment_amount: 100.0
alerts:
  enable: true
  lookback_minutes: 120
price_levels:
  enable: true
  levels: {}
timing:
  check_interval: 900
logging:
  file: logs/crypto_bot.log
  level: INFO
