telegram:
  bot_token: 8296923394:AAH4GIdVUFp14kpAA0ifqaDwRErsJKu6kls
  chat_id: '6574539700'
crypto:
  symbols:
  - BTC
  - ETH
  - SOL
  investment_amount: 100.0
alerts:
  enable: true
  lookback_minutes: 120
price_levels:
  enable: true
  levels: {}
timing:
  check_interval: 900
logging:
  file: logs/crypto_bot.log
  level: INFO
