# Configuration des notifications
# Activez/désactivez les blocs selon vos besoins

notifications:
  enabled: true
  kid_friendly_mode: true
  use_emojis_everywhere: true
  explain_everything: true
  respect_quiet_hours: true
  quiet_start: 23
  quiet_end: 7
  default_scheduled_hours: [9, 12, 18]

# Configuration par crypto
coins:
  BTC:
    enabled: true
    nickname: "Bitcoin"
    custom_emoji: "₿"
    
    scheduled_notifications:
      - name: "Notification principale"
        enabled: true
        hours: [9, 12, 18]
        days_of_week: [0, 1, 2, 3, 4, 5, 6]
        
        # Ordre d'affichage des blocs
        blocks_order:
          - header
          - price
          - prediction
          - opportunity
          - brokers      # ← ACTIVÉ
          - footer
        
        header_message: "🔔 {symbol} - Mise à jour"
        footer_message: "ℹ️ Ceci n'est pas un conseil financier"
        
        # Configuration de chaque bloc
        price_block:
          enabled: true
          show_price_eur: true
          show_variation_24h: true
          show_variation_7d: false
          show_volume: true
          show_market_cap: false
          add_price_comment: false
        
        chart_block:
          enabled: false  # ← DÉSACTIVÉ
        
        prediction_block:
          enabled: true
          show_prediction_type: true
          show_confidence: true
          min_confidence_to_show: 50
        
        opportunity_block:
          enabled: true
          show_score: true
          show_recommendation: true
          show_reasons: false
          min_score_to_show: 0
        
        brokers_block:
          enabled: true              # ← ACTIVÉ ICI
          title: "💱 Prix sur les brokers"
          show_best_price: true
          show_all_brokers: true
          show_fees: true
          max_brokers_displayed: 5
          explanation: "Comparaison des prix sur différentes plateformes"
        
        fear_greed_block:
          enabled: false  # ← DÉSACTIVÉ
        
        gain_loss_block:
          enabled: false  # ← DÉSACTIVÉ
        
        investment_suggestions_block:
          enabled: false  # ← DÉSACTIVÉ
        
        glossary_block:
          enabled: false  # ← DÉSACTIVÉ
  
  ETH:
    enabled: true
    nickname: "Ethereum"
    custom_emoji: "🦄"
    
    scheduled_notifications:
      - name: "Notification ETH"
        enabled: true
        hours: [9, 18]
        
        blocks_order:
          - header
          - price
          - brokers
          - footer
        
        price_block:
          enabled: true
        
        brokers_block:
          enabled: true
  
  SOL:
    enabled: true
    nickname: "Solana"
    custom_emoji: "⚡"
    
    scheduled_notifications:
      - name: "Notification SOL"
        enabled: true
        hours: [9, 18]
        
        blocks_order:
          - header
          - price
          - brokers
          - footer
        
        price_block:
          enabled: true
        
        brokers_block:
          enabled: true
